## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##

coreo_aws_ec2_securityGroups "vpn-elb-sg" do
  action :sustain
  description "Open vpn to the world"
  vpc "${VPC_NAME}"
  allows [ 
          { 
            :direction => :ingress,
            :protocol => :tcp,
            :ports => [1199],
            :cidrs => ["0.0.0.0/0"],
          },{ 
            :direction => :egress,
            :protocol => :tcp,
            :ports => ["0..65535"],
            :cidrs => ["0.0.0.0/0"],
          }
    ]
end

coreo_aws_ec2_elb "vpn-elb" do
  action :sustain
  type "public"
  vpc "${VPC_NAME}"
  subnet "${PUBLIC_SUBNET_NAME}"
  security_groups ["vpn-elb-sg"]
  listeners [
             {
               :elb_protocol => 'tcp', 
               :elb_port => 1199, 
               :to_protocol => 'tcp', 
               :to_port => 1199
             }
            ]
  health_check_protocol 'tcp'
  health_check_port "1199"
end

coreo_aws_route53_record "vpn-prod" do
  action :sustain
  type "CNAME"
  zone "creditshop.com"
  values ["STACK::coreo_aws_ec2_elb.vpn-elb.dns_name"]
end

coreo_aws_ec2_securityGroups "vpn-sg" do
  action :sustain
  description "Open vpn connections to the world"
  vpc "${VPC_NAME}"
  allows [ 
          { 
            :direction => :ingress,
            :protocol => :tcp,
            :ports => [1199],
            :groups => ["vpn-elb-sg"],
          },{ 
            :direction => :ingress,
            :protocol => :tcp,
            :ports => [22],
            :cidrs => ["10.0.0.0/8"],
          },{ 
            :direction => :egress,
            :protocol => :tcp,
            :ports => ["0..65535"],
            :cidrs => ["0.0.0.0/0"],
          }
    ]
end

coreo_aws_iam_policy "vpn" do
  action :sustain
  policy_name "AllowRoute53Management"
  policy_document <<-EOH
{
  "Statement": [
    {
      "Effect": "Allow",
      "Resource": [
          "*"
      ],
      "Action": [ 
          "route53:*"
      ]
    }
  ]
}
EOH
end

coreo_aws_iam_instance_profile "vpn" do
  action :sustain
  policies ["vpn"]
end

coreo_aws_ec2_instance "vpn" do
  action :define
  image_id "ami-802095e8"
  size "t1.micro"
  security_groups ["vpn-sg"]
  ssh_key "tools-prod"
  role "vpn"
  disable_cc_client true
end

coreo_aws_ec2_autoscaling "vpn" do
  action :sustain 
  minimum 1
  maximum 1
  server_definition "vpn"
  subnet "${PRIVATE_SUBNET_NAME}"
  elbs ["vpn-elb"]
end
